Fungus dialog integration
motzca/SeniorDesignProject_AnimalVilla pull request #10
Opened 2024-02-07 02:05 UTC by motzca

2024-02-28 23:30 UTC, motzca commented
@BeanDevStudios This doesn't seem to actually be connected to the cards at all, like you implied. Instead, it rests on top of the cards. It almost feels like playing two games at once because you can play around with the card and get those to update while the Fungus dialogue is placed on top. 

Furthermore, if you plan on implementing buttons instead of the swipes, this is something that needs to be discussed with the whole development team. It took me by surprise to see it being done in button form.

2024-02-29 15:16 UTC, BeanDevStudios commented
> @BeanDevStudios This doesn't seem to actually be connected to the cards at all, like you implied. Instead, it rests on top of the cards. It almost feels like playing two games at once because you can play around with the card and get those to update while the Fungus dialogue is placed on top.
> 
> Furthermore, if you plan on implementing buttons instead of the swipes, this is something that needs to be discussed with the whole development team. It took me by surprise to see it being done in button form.

Dialog that appears to be overlayed ontop of the cards/game area is only proof of concept that Fungus can recognize the swipe system. This overlay will not appear once story is added and instead will appear at the bottom of the card. This will be added on 3/2/2024. Also, there will be no additional buttons. The overlay that shows what direction the player swiped is called a "Say" module, which automatically comes with a button. This "Say" module will be replaced with sory functionallity as it is just a place holder.

2024-03-01 19:35 UTC, L0ST201 commented
Until the dialogue system (Fungus) is properly integrated with our game's card-swiping mechanics, there is a limited ability to conduct a comprehensive review. As Chloe highlighted, there is a lack of readiness for a code review or a proof of concept for Fungus and the swipe mechanic because there is no indication that integration is occurring at this time. In its current sate this pr is not ready to be merged into the main branch.

Additionally, I recommend avoiding the inclusion of demo files and assets in pull requests. These files tend to clutter the project and make it more difficult to locate and assess the core changes. It's crucial that pull requests do not include these, as it maintains a clean codebase which significantly streamlines the review process and is important to note I will not merge PRs with unnecessary files to keep a clean codebase.

As a final note for the future I strongly recommend adopting a practice of creating new branches off the main branch for individual work, such as feature development / bug fixes, and then incorporating changes from various branches, like Fungus Dialogue Integration, into these newly created personal branches rather than directly working on shared branches. This approach allows for greater freedom in making modifications without the risk of inadvertently overwriting someone else's contributions or causing unexpected conflicts or code leaks. It promotes a more organized and efficient workflow, ensuring that each team member's work remains isolated until it's ready to be shared or merged. This method not only facilitates smoother collaboration by minimizing potential for conflict and confusion but also safeguards the integrity of ongoing work by clearly delineating responsibility and ownership over specific portions of the project.

2024-03-01 19:38 UTC, L0ST201 requested changes
My initial comment indicates as why changes are requested.

2024-03-04 01:35 UTC, motzca commented
The text seems to be updating now, however, is there only one block attached? The same block of text seems to be returned. I'm also running into an issue where I'm getting the error below to pop up every time I swipe a card. Besides that, it seems to be functioning appropriately
![Capture](https://github.com/motzca/SeniorDesignProject_AnimalVilla/assets/88688697/9bc317f7-e785-411a-b5bc-6f38074ad788)

2024-03-04 21:21 UTC, L0ST201 commented
@BeanDevStudios I just wanted to reiterate, as mentioned in my previous comment before the branch is merged to main, could you remove the demo files and assets? They significantly clutter the project and add irrelevant data to it and just makes it a pain to look through in general. Thanks!

2024-03-06 23:39 UTC, L0ST201 approved these changes
looks good

2024-03-06 23:40 UTC, merged