Adding EndingManager + Starting to incorporate it into the GameManager
motzca/SeniorDesignProject_AnimalVilla pull request #12
Opened 2024-03-01 04:21 UTC by motzca

2024-03-12 02:17 UTC, L0ST201 requested changes
In addition on line 132 we could do the following:

```
public void UpdateMoney(int change)
{
    int newMoneyStatus = Mathf.Clamp(MoneyStatus + change, MinValue, MaxValue);
    if (MoneyStatus != newMoneyStatus)
    {
        MoneyStatus = newMoneyStatus;
        OnMoneyZero?.Invoke(endingMoneyCardId); 
    }
}
```

Updating `UpdateMoney`, `UpdateEnergy`, and `UpdateReputation` methods using the above as an example provides several enhancements that collectively improve the game's logic and code quality. This ensures that updates and event triggers only occur following actual changes, eliminating unnecessary operations that could worsen the game's performance. I also think the use of the null-conditional operator for event invocation simplifies the code by removing the need for explicit null checks, streamlining event handling.

2024-03-12 02:17 UTC, LostInTyping commented on Assets/Scripts/Game/EndingManager.cs
> +            OnMoneyZero(endingMoneyCardId);
In the current implementation, you manually check for null before invoking events, which, while functional, adds unnecessary lines to our codebase. I recommend adopting the null conditional operator (?.) for event invocation, like this:
```
if (GameManager.MoneyStatus <= 0)
{
    OnMoneyZero?.Invoke(endingMoneyCardId);
}
```
I think it enhances the readability to the code, improves the safety because using ?, we automatically bypass the event invocation if it's null, thus eliminating the risk of encountering a NullReferenceException, and lastly using the conditional operator aligns our code with current best practices.

Do this for all 3

2024-03-12 02:17 UTC, LostInTyping commented on Assets/Scripts/Game/EndingManager.cs
> +        else if (GameManager.EnergyStatus <= 0 && OnEnergyZero != null)
To better manage game stat changes, we should utilize individual `if` statements for each condition. This approach allows for simultaneous triggering of multiple events, which I think will enhances the clarity of the code, and guarantees a more precise and responsive game state management. In the current implementation I believe this is fine but we can have more varied endings easier if we watch all stats in the future but not a big deal either way currently.

2024-03-12 02:17 UTC, L0ST201 commented on Assets/Scripts/Game/StatusChecker.cs
> +    void Update()
Instead oh having everything in update maybe we should introduced a new method and call it CheckForStatusZero to encapsulate status checks, keeping Update clean and focused on just calling the method.

so do somthing like this? 

```  
void Update()
    {
        CheckForStatusZero();
    }

    private void CheckForStatusZero()
    {
        if (GameManager.MoneyStatus <= 0)
        {
            LoadSpecialEndingCard(moneyZeroCard);
            return;
        }

        if (GameManager.EnergyStatus <= 0)
        {
            LoadSpecialEndingCard(energyZeroCard);
            return;
        }

        if (GameManager.ReputationStatus <= 0)
        {
            LoadSpecialEndingCard(reputationZeroCard);
            return;
        }
    }
```

2024-03-12 02:17 UTC, L0ST201 commented on Assets/Scripts/Game/GameManager.cs
> +        if (MoneyStatus <= 0 && OnMoneyZero != null)
same as in EndingManager.cs what if we do: 

```
if (GameManager.MoneyStatus <= 0)
{
    OnMoneyZero?.Invoke(endingMoneyCardId);
}

if (GameManager.EnergyStatus <= 0)
{
    OnEnergyZero?.Invoke(endingEnergyCardId);
}

if (GameManager.ReputationStatus <= 0)
{
    OnReputationZero?.Invoke(endingReputationCardId);
}
```

2024-03-24 14:38 UTC, motzca commented
@L0ST201 Just to let you know, when resetting back to the beginning, it takes a few seconds to restart the full game. If needed, I can try to modify that code so that it runs smoother.

2024-03-24 19:44 UTC, L0ST201 commented
There are a few problems. 

- [ ] 1. Currently the game does not Restart it sends errors this looks like you have it targeting scene `MainMenu` When this doesn't exist and is just `Start`.
- [ ] 2. The game on Restart doesn't Currently Reset stats and keeps them at there current state when they should reset to default.
![image](https://github.com/motzca/SeniorDesignProject_AnimalVilla/assets/82691998/6a9a9a65-f7ec-4477-8269-98e5db974ed2)
![image](https://github.com/motzca/SeniorDesignProject_AnimalVilla/assets/82691998/1254481e-ee43-4518-b7a2-5eee6449cc99)

- [ ] Text falls outside of text box.

2024-03-25 17:53 UTC, merged