New Features + More Refactors + so much more
motzca/SeniorDesignProject_AnimalVilla pull request #9
Opened 2024-01-31 06:08 UTC by L0ST201

2024-02-19 22:54 UTC, motzca commented
The leftQuote and rightQuote are no longer working. Whenever I move the card to the left or right, the words 'Demo Text' is still there and it doesn't actually present the correct dialogue options. Also, when moving the card left and right, it has shaky movement when it gets closer to the edge of the box. This could cause problems in the future.

2024-02-19 22:55 UTC, motzca requested changes
The leftQuote and rightQuote are no longer working. Whenever I move the card to the left or right, the words 'Demo Text' is still there and it doesn't actually present the correct dialogue options. 

Also, when moving the card left and right, it has shaky movement when it gets closer to the edge of the box. This could cause problems in the future.

2024-02-19 23:49 UTC, L0ST201 commented
I had removed Action Dialogue but added it back in, so that is fixed.

The shakiness will likely only happen on PC, but will require more debugging time. Due to the amount of changes, I think it's acceptable to add that issue with M&KB issue when it's only effected on the edge of the screen.

2024-02-21 00:46 UTC, motzca approved these changes

2024-02-21 00:46 UTC, merged